// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: x2 v0.2.0

import { Reactor, FileRef } from "@reactor-team/js-sdk";
export { FileRef };

export const MODEL_NAME = "xmax/x2" as const;
export const MODEL_VERSION = "v0.2.0" as const;

/**
 * Preset media tracks for the X2 model.
 *
 * Declared in the model's OpenAPI schema and passed to the SDK as
 * `modelTracks` so the transport can prepare the SDP offer in
 * parallel with session polling (faster first-frame latency).
 */
export const X2Tracks = [
  { name: "source", kind: "video", direction: "sendonly" },
  { name: "main_video", kind: "video", direction: "recvonly" },
] as const;

/** Track names the client can publish into (sendonly, from the client's perspective). */
export type X2SendTrackName =
  "source";

/** Track names the client can subscribe to (recvonly, from the client's perspective). */
export type X2RecvTrackName =
  "main_video";

/** Set the editing instruction that guides the re-render (for example a character swap or insertion). A non-empty prompt is required before generation begins; setting it while generating applies from the next block. Emits `prompt_accepted`, then `state_update`. */
export interface X2SetPromptParams {
  /**
   * The editing instruction, e.g. "replace the person with the character from the reference image". Up to 1000 characters. Applies from the next generated block.
   * @maxLength 1000
   * @default ""
   */

  prompt?: string;
}

/** Provide a reference image of a character or object to insert or swap into the video. Can be set before generation or replaced while generating; replacing it mid-run restarts the stream (`generation_stopped` with reason `reference_image_changed`, then a fresh `generation_started`) so the new reference conditions it from the first block. Emits `reference_image_accepted` and `state_update` on success, or `command_error` if the file cannot be decoded as an image. */
export interface X2SetReferenceImageParams {
  /** Reference to a file uploaded via the Reactor presigned-URL protocol. */

  reference_image: FileRef;
}

/** Update the drag pointer that steers the edited subject's motion, setting its position and press state together. Valid any time; the pointer is sampled once per generated block and only has an effect while active. Emits `pointer_changed`, then `state_update`. */
export interface X2SetPointerParams {
  /**
   * Horizontal pointer position, normalized to the output frame (0 = left, 1 = right).
   * @minimum 0
   * @maximum 1
   * @default 0.5
   */

  x?: number;
  /**
   * Vertical pointer position, normalized to the output frame (0 = top, 1 = bottom).
   * @minimum 0
   * @maximum 1
   * @default 0.5
   */

  y?: number;
  /**
   * Whether a drag gesture is in progress. While true, the pointer steers motion; while false, it is ignored.
   * @default false
   */

  active?: boolean;
}

/** Set pointer_x */
export interface X2SetPointerXParams {
  /**
   * Horizontal drag-pointer position, normalized to the output frame (0 = left edge, 1 = right edge). Sampled once per generated block and only steers motion while `pointer_active` is true.
   * @minimum 0
   * @maximum 1
   * @default 0.5
   */

  pointer_x?: number;
}

/** Set pointer_y */
export interface X2SetPointerYParams {
  /**
   * Vertical drag-pointer position, normalized to the output frame (0 = top edge, 1 = bottom edge). Sampled once per generated block and only steers motion while `pointer_active` is true.
   * @minimum 0
   * @maximum 1
   * @default 0.5
   */

  pointer_y?: number;
}

/** Set pointer_active */
export interface X2SetPointerActiveParams {
  /**
   * Whether a drag gesture is in progress. While true, the current `pointer_x`/`pointer_y` position steers the motion of the edited subject; while false, the pointer is ignored. Sampled once per generated block.
   * @default false
   */

  pointer_active?: boolean;
}

/** Set keep_backlog */
export interface X2SetKeepBacklogParams {
  /**
   * Source-frame consumption policy, applied from the next block. False (default): always read the newest frames and drop backlog, keeping latency bounded when inference is slower than the source. True: consume every frame in order for smoother motion (e.g. drag mode) at the cost of growing delay.
   * @default false
   */

  keep_backlog?: boolean;
}

/** Emitted after `set_prompt` succeeds; echoes the accepted prompt. */
export interface X2PromptAcceptedMessage {
  type: "prompt_accepted";
  /** The editing instruction now in effect. It conditions generation from the next block onward. */

  prompt: string;
}

/** Emitted after `set_reference_image` decodes an uploaded image. */
export interface X2ReferenceImageAcceptedMessage {
  type: "reference_image_accepted";
  /** Width, in pixels, of the decoded reference image, before it is fitted to the output resolution. */

  width: number;
  /** Height, in pixels, of the decoded reference image, before it is fitted to the output resolution. */

  height: number;
}

/** Emitted after `set_pointer` updates the drag pointer. */
export interface X2PointerChangedMessage {
  type: "pointer_changed";
  /** Horizontal pointer position, normalized to the output frame (0 = left, 1 = right). */

  x: number;
  /** Vertical pointer position, normalized to the output frame (0 = top, 1 = bottom). */

  y: number;
  /** Whether a drag gesture is in progress. While true, the pointer steers the edited subject's motion. */

  active: boolean;
}

/** Emitted once when a generation run begins producing `main_video`. */
export interface X2GenerationStartedMessage {
  type: "generation_started";
  /** The editing instruction the run started with. */

  prompt: string;
  /** Output frame width in pixels. Chosen once at the first generation and fixed for the whole session. */

  width: number;
  /** Output frame height in pixels. Chosen once at the first generation and fixed for the whole session. */

  height: number;
  /** Whether a reference image is conditioning this run. */

  has_reference_image: boolean;
}

/** Emitted when a generation run ends; no more `main_video` frames follow until it restarts. */
export interface X2GenerationStoppedMessage {
  type: "generation_stopped";
  /** Why generation stopped: `reset` (cleared by the `reset` command) or `reference_image_changed` (a new reference image triggered an automatic restart, and a fresh `generation_started` follows). */

  reason: string;
}

/** Emitted when a command cannot be applied; the command has no effect. */
export interface X2CommandErrorMessage {
  type: "command_error";
  /** Name of the command that failed, e.g. `set_reference_image`. */

  command: string;
  /** Human-readable explanation of why the command was rejected. */

  reason: string;
}

/** Emitted on connect and after every observable state change; carries the full state in one payload. */
export interface X2StateUpdateMessage {
  type: "state_update";
  /** The active editing instruction, or null when none is set. Generation does not run without a prompt. */

  prompt: unknown;
  /** Whether a reference image is currently conditioning generation. */

  has_reference_image: boolean;
  /** Current horizontal drag-pointer position, normalized to the output frame (0 = left, 1 = right). */

  pointer_x: number;
  /** Current vertical drag-pointer position, normalized to the output frame (0 = top, 1 = bottom). */

  pointer_y: number;
  /** Whether a drag gesture is currently steering the edited subject. */

  pointer_active: boolean;
  /** Current source-frame policy. False: read the newest frames and drop backlog (bounded latency). True: consume every frame in order (smoother motion, growing delay). */

  keep_backlog: boolean;
  /** Whether a generation run is currently producing `main_video` frames. */

  generating: boolean;
  /** Output frame width in pixels once a run has started, or null before the resolution is chosen. Fixed for the whole session. */

  width: unknown;
  /** Output frame height in pixels once a run has started, or null before the resolution is chosen. Fixed for the whole session. */

  height: unknown;
}

export type X2Message =
  | X2PromptAcceptedMessage
  | X2ReferenceImageAcceptedMessage
  | X2PointerChangedMessage
  | X2GenerationStartedMessage
  | X2GenerationStoppedMessage
  | X2CommandErrorMessage
  | X2StateUpdateMessage;

/**
 * Options for creating a X2Model (model name is set automatically).
 *
 * Derived from `Reactor`'s own constructor options with `modelName`
 * and `modelTracks` removed — those are supplied by this class.
 * Any new option the SDK adds appears here automatically on the
 * next `defaultSdkVersion` bump.
 */
export type X2Options = Omit<
  ConstructorParameters<typeof Reactor>[0],
  "modelName" | "modelTracks"
>;

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Strongly-typed client for the X2 model.
 *
 * Extends {@link Reactor} with the model name (and modelTracks) baked into the
 * constructor, so every public method on Reactor — `connect`, `disconnect`,
 * `sendCommand`, `on`/`off`, `getStats`, `publishTrack`/`unpublishTrack`,
 * etc. — is reachable directly on the instance. The schema-derived sugar
 * below adds typed wrappers for every declared event, message, and track.
 */

export class X2Model extends Reactor {
  constructor(options?: X2Options) {
    super({
      ...options,
      modelName: MODEL_NAME,
      modelTracks: [...X2Tracks],
    });
  }

  /** @deprecated The model client now extends `Reactor` directly — call methods on `this` instead. This accessor returns `this` for backwards compatibility and will be removed in a future major release. */

  get reactor(): this {
    return this;
  }

  /**
   * Set the editing instruction that guides the re-render (for example a character swap or insertion). A non-empty prompt is required before generation begins; setting it while generating applies from the next block. Emits `prompt_accepted`, then `state_update`.
   * @param params - Set the editing instruction that guides the re-render (for example a character swap or insertion). A non-empty prompt is required before generation begins; setting it while generating applies from the next block. Emits `prompt_accepted`, then `state_update`.
   */

  async setPrompt(params: X2SetPromptParams): Promise<void> {
    await this.sendCommand("set_prompt", params);
  }

  /**
   * Provide a reference image of a character or object to insert or swap into the video. Can be set before generation or replaced while generating; replacing it mid-run restarts the stream (`generation_stopped` with reason `reference_image_changed`, then a fresh `generation_started`) so the new reference conditions it from the first block. Emits `reference_image_accepted` and `state_update` on success, or `command_error` if the file cannot be decoded as an image.
   * @param params - Provide a reference image of a character or object to insert or swap into the video. Can be set before generation or replaced while generating; replacing it mid-run restarts the stream (`generation_stopped` with reason `reference_image_changed`, then a fresh `generation_started`) so the new reference conditions it from the first block. Emits `reference_image_accepted` and `state_update` on success, or `command_error` if the file cannot be decoded as an image.
   */

  async setReferenceImage(params: X2SetReferenceImageParams): Promise<void> {
    await this.sendCommand("set_reference_image", params);
  }

  /**
   * Update the drag pointer that steers the edited subject's motion, setting its position and press state together. Valid any time; the pointer is sampled once per generated block and only has an effect while active. Emits `pointer_changed`, then `state_update`.
   * @param params - Update the drag pointer that steers the edited subject's motion, setting its position and press state together. Valid any time; the pointer is sampled once per generated block and only has an effect while active. Emits `pointer_changed`, then `state_update`.
   */

  async setPointer(params: X2SetPointerParams): Promise<void> {
    await this.sendCommand("set_pointer", params);
  }

  /** Stop generation and clear the prompt, reference image, and pointer, returning the session to waiting for new conditions. Valid any time. Emits `generation_stopped` with reason `reset` if a run was active, and `state_update`. */

  async reset(): Promise<void> {
    await this.sendCommand("reset", {});
  }

  /**
   * Set pointer_x
   * @param params - Set pointer_x
   */

  async setPointerX(params: X2SetPointerXParams): Promise<void> {
    await this.sendCommand("set_pointer_x", params);
  }

  /**
   * Set pointer_y
   * @param params - Set pointer_y
   */

  async setPointerY(params: X2SetPointerYParams): Promise<void> {
    await this.sendCommand("set_pointer_y", params);
  }

  /**
   * Set pointer_active
   * @param params - Set pointer_active
   */

  async setPointerActive(params: X2SetPointerActiveParams): Promise<void> {
    await this.sendCommand("set_pointer_active", params);
  }

  /**
   * Set keep_backlog
   * @param params - Set keep_backlog
   */

  async setKeepBacklog(params: X2SetKeepBacklogParams): Promise<void> {
    await this.sendCommand("set_keep_backlog", params);
  }

  /**
   * Subscribe to typed model messages.
   * @param handler - Called with a discriminated X2Message
   * @returns Unsubscribe function
   */

  onMessage(handler: (message: X2Message) => void): () => void {
    const wrappedHandler = (raw: unknown) => {
      handler(_unwrapMessage<X2Message>(raw));
    };
    this.on("message", wrappedHandler);
    return () => this.off("message", wrappedHandler);
  }

  /**
   * Subscribe to "prompt_accepted" messages only.
   * @returns Unsubscribe function
   */

  onPromptAccepted(handler: (message: X2PromptAcceptedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "prompt_accepted") handler(msg as X2PromptAcceptedMessage);
    });
  }

  /**
   * Subscribe to "reference_image_accepted" messages only.
   * @returns Unsubscribe function
   */

  onReferenceImageAccepted(handler: (message: X2ReferenceImageAcceptedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "reference_image_accepted") handler(msg as X2ReferenceImageAcceptedMessage);
    });
  }

  /**
   * Subscribe to "pointer_changed" messages only.
   * @returns Unsubscribe function
   */

  onPointerChanged(handler: (message: X2PointerChangedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "pointer_changed") handler(msg as X2PointerChangedMessage);
    });
  }

  /**
   * Subscribe to "generation_started" messages only.
   * @returns Unsubscribe function
   */

  onGenerationStarted(handler: (message: X2GenerationStartedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "generation_started") handler(msg as X2GenerationStartedMessage);
    });
  }

  /**
   * Subscribe to "generation_stopped" messages only.
   * @returns Unsubscribe function
   */

  onGenerationStopped(handler: (message: X2GenerationStoppedMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "generation_stopped") handler(msg as X2GenerationStoppedMessage);
    });
  }

  /**
   * Subscribe to "command_error" messages only.
   * @returns Unsubscribe function
   */

  onCommandError(handler: (message: X2CommandErrorMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "command_error") handler(msg as X2CommandErrorMessage);
    });
  }

  /**
   * Subscribe to "state_update" messages only.
   * @returns Unsubscribe function
   */

  onStateUpdate(handler: (message: X2StateUpdateMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "state_update") handler(msg as X2StateUpdateMessage);
    });
  }

  /**
   * Start sending a video track to the model's "source" sendonly channel.
   *
   * Pass a live MediaStreamTrack (e.g. from `getUserMedia({ video: true })`).
   * Safe to call repeatedly — the transport `replaceTrack()`s the new value onto the existing RTCRtpSender without renegotiating.
   * @param track - The video MediaStreamTrack to publish
   */

  async publishSource(track: MediaStreamTrack): Promise<void> {
    await this.publishTrack("source", track);
  }

  /**
   * Stop sending on the "source" sendonly channel.
   *
   * The underlying RTCRtpSender stays alive — future `publishSource()` calls resume on the same transceiver without renegotiating.
   */

  async unpublishSource(): Promise<void> {
    await this.unpublishTrack("source");
  }

  /**
   * Subscribe to the "main_video" recvonly video track the model publishes.
   *
   * The handler fires once the model starts publishing this track; it receives the live MediaStreamTrack and the parent MediaStream (useful for attaching to a `<video>` / `<audio>` element via `srcObject`).
   * @param handler - Called with the received track and its stream
   * @returns Unsubscribe function
   */

  onMainVideo(
    handler: (track: MediaStreamTrack, stream: MediaStream) => void,
  ): () => void {
    const wrapped = (name: string, t: MediaStreamTrack, s: MediaStream) => {
      if (name === "main_video") handler(t, s);
    };
    this.on("trackReceived", wrapped);
    return () => this.off("trackReceived", wrapped);
  }
}
