// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: x2 v0.2.0

"use client";

import { type ReactElement } from "react";
import {
  ReactorProvider,
  useReactor,
  useReactorMessage,
  ReactorView,
  type ReactorViewProps,
  WebcamStream,
  type WebcamStreamProps,
} from "@reactor-team/js-sdk";
import {
  MODEL_NAME,
  X2Tracks,
  type X2Options,
  type X2SetPromptParams,
  type X2SetReferenceImageParams,
  type X2SetPointerParams,
  type X2SetPointerXParams,
  type X2SetPointerYParams,
  type X2SetPointerActiveParams,
  type X2SetKeepBacklogParams,
  type X2Message,
  type X2PromptAcceptedMessage,
  type X2ReferenceImageAcceptedMessage,
  type X2PointerChangedMessage,
  type X2GenerationStartedMessage,
  type X2GenerationStoppedMessage,
  type X2CommandErrorMessage,
  type X2StateUpdateMessage,
  type X2RecvTrackName,
} from "./sdk";

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Props for the {@link X2Provider} component.
 *
 * Derived from `ReactorProvider`'s own props, with `modelName` and
 * `modelTracks` stripped — those are supplied by this provider.
 */
export type X2ProviderProps = Omit<
  Parameters<typeof ReactorProvider>[0],
  "modelName" | "modelTracks"
>;

/**
 * Provider for the X2 model.
 *
 * Wraps {@link ReactorProvider} with `modelName` and `modelTracks` pre-configured from the
 * generated constants. Drop this near the top of your tree, then use
 * {@link useX2} and the `useX2<Message>` hooks below it.
 */
export function X2Provider({
  children,
  ...rest
}: X2ProviderProps): ReactElement {
  return (
    <ReactorProvider
      {...rest}
      modelName={MODEL_NAME}
      modelTracks={[...X2Tracks]}
    >
      {children}
    </ReactorProvider>
  );
}

/**
 * Access the X2 model as typed commands bound to the nearest
 * {@link X2Provider}.
 *
 * Returns the full action surface — every public field on the SDK's
 * `ReactorStore` (`status`, `sessionId`, `connect`, `disconnect`,
 * `sendCommand`, `uploadFile`, `publish`, `unpublish`, `reconnect`,
 * …) is exposed automatically, alongside one typed method per
 * model event.
 *
 * Fields are pulled off the store one at a time so Zustand's
 * shallow-equality selector keeps each subscription scoped — a
 * component reading only `status` doesn't re-render when
 * `sessionExpiration` changes. Future SDK releases that add new
 * store fields flow into this hook on the next codegen run with no
 * hand-edit (the field list is derived from `js-sdk`'s d.ts via
 * `loadReactorStoreFieldsFromDts` in `sdk-surface.ts`).
 */
export function useX2() {
  const connect = useReactor((s) => s.connect);
  const connectOptions = useReactor((s) => s.connectOptions);
  const disconnect = useReactor((s) => s.disconnect);
  const downloadClipAsFile = useReactor((s) => s.downloadClipAsFile);
  const jwtToken = useReactor((s) => s.jwtToken);
  const lastError = useReactor((s) => s.lastError);
  const publish = useReactor((s) => s.publish);
  const reconnect = useReactor((s) => s.reconnect);
  const requestClip = useReactor((s) => s.requestClip);
  const requestRecording = useReactor((s) => s.requestRecording);
  const sendCommand = useReactor((s) => s.sendCommand);
  const sessionExpiration = useReactor((s) => s.sessionExpiration);
  const sessionId = useReactor((s) => s.sessionId);
  const status = useReactor((s) => s.status);
  const tracks = useReactor((s) => s.tracks);
  const unpublish = useReactor((s) => s.unpublish);
  const uploadFile = useReactor((s) => s.uploadFile);

  return {
    connect,
    connectOptions,
    disconnect,
    downloadClipAsFile,
    jwtToken,
    lastError,
    publish,
    reconnect,
    requestClip,
    requestRecording,
    sendCommand,
    sessionExpiration,
    sessionId,
    status,
    tracks,
    unpublish,
    uploadFile,
    setPrompt: (params: X2SetPromptParams): Promise<void> =>
      sendCommand("set_prompt", params),
    setReferenceImage: (params: X2SetReferenceImageParams): Promise<void> =>
      sendCommand("set_reference_image", params),
    setPointer: (params: X2SetPointerParams): Promise<void> =>
      sendCommand("set_pointer", params),
    reset: (): Promise<void> => sendCommand("reset", {}),
    setPointerX: (params: X2SetPointerXParams): Promise<void> =>
      sendCommand("set_pointer_x", params),
    setPointerY: (params: X2SetPointerYParams): Promise<void> =>
      sendCommand("set_pointer_y", params),
    setPointerActive: (params: X2SetPointerActiveParams): Promise<void> =>
      sendCommand("set_pointer_active", params),
    setKeepBacklog: (params: X2SetKeepBacklogParams): Promise<void> =>
      sendCommand("set_keep_backlog", params),
  };
}

/**
 * Subscribe to any X2 message with a fully-typed handler.
 * The handler receives a discriminated X2Message.
 */
export function useX2Message(handler: (message: X2Message) => void): void {
  useReactorMessage((msg: unknown) => handler(_unwrapMessage<X2Message>(msg)));
}

/**
 * Subscribe to "prompt_accepted" messages only.
 * Handler receives a fully-typed X2PromptAcceptedMessage.
 */
export function useX2PromptAccepted(
  handler: (message: X2PromptAcceptedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<X2Message>(msg);
    if (m.type === "prompt_accepted") {
      handler(m as X2PromptAcceptedMessage);
    }
  });
}

/**
 * Subscribe to "reference_image_accepted" messages only.
 * Handler receives a fully-typed X2ReferenceImageAcceptedMessage.
 */
export function useX2ReferenceImageAccepted(
  handler: (message: X2ReferenceImageAcceptedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<X2Message>(msg);
    if (m.type === "reference_image_accepted") {
      handler(m as X2ReferenceImageAcceptedMessage);
    }
  });
}

/**
 * Subscribe to "pointer_changed" messages only.
 * Handler receives a fully-typed X2PointerChangedMessage.
 */
export function useX2PointerChanged(
  handler: (message: X2PointerChangedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<X2Message>(msg);
    if (m.type === "pointer_changed") {
      handler(m as X2PointerChangedMessage);
    }
  });
}

/**
 * Subscribe to "generation_started" messages only.
 * Handler receives a fully-typed X2GenerationStartedMessage.
 */
export function useX2GenerationStarted(
  handler: (message: X2GenerationStartedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<X2Message>(msg);
    if (m.type === "generation_started") {
      handler(m as X2GenerationStartedMessage);
    }
  });
}

/**
 * Subscribe to "generation_stopped" messages only.
 * Handler receives a fully-typed X2GenerationStoppedMessage.
 */
export function useX2GenerationStopped(
  handler: (message: X2GenerationStoppedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<X2Message>(msg);
    if (m.type === "generation_stopped") {
      handler(m as X2GenerationStoppedMessage);
    }
  });
}

/**
 * Subscribe to "command_error" messages only.
 * Handler receives a fully-typed X2CommandErrorMessage.
 */
export function useX2CommandError(
  handler: (message: X2CommandErrorMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<X2Message>(msg);
    if (m.type === "command_error") {
      handler(m as X2CommandErrorMessage);
    }
  });
}

/**
 * Subscribe to "state_update" messages only.
 * Handler receives a fully-typed X2StateUpdateMessage.
 */
export function useX2StateUpdate(
  handler: (message: X2StateUpdateMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<X2Message>(msg);
    if (m.type === "state_update") {
      handler(m as X2StateUpdateMessage);
    }
  });
}

/**
 * Subscribe to a recvonly MediaStreamTrack the model publishes, by name.
 *
 * Returns `undefined` until the model emits the track, then the live track for the lifetime of the connection. `name` is constrained to the model's declared recvonly channels — use one of `X2RecvTrackName`.
 * @param name - A recvonly track name declared by the model
 * @returns The live MediaStreamTrack, or `undefined` until received
 */
export function useX2Track(
  name: X2RecvTrackName,
): MediaStreamTrack | undefined {
  return useReactor((s) => s.tracks[name]);
}

export type X2MainVideoViewProps = Omit<ReactorViewProps, "track">;

/**
 * Render the model's "main_video" recvonly video track in a `<video>` element.
 *
 * Thin wrapper around `<ReactorView>` with `track` pre-bound. Accepts every other `ReactorViewProps` (`audioTrack`, `className`, `style`, `videoObjectFit`, `muted`, …). Must be rendered inside `<X2Provider>`.
 */
export function X2MainVideoView(props: X2MainVideoViewProps): ReactElement {
  return <ReactorView {...props} track="main_video" />;
}

export type X2SourceViewProps = Omit<WebcamStreamProps, "track">;

/**
 * Acquire the user's webcam and publish it to the model's "source" sendonly video channel.
 *
 * Thin wrapper around `<WebcamStream>` with `track` pre-bound. Requests `getUserMedia()` on mount, auto-publishes when the connection reaches `ready`, cleans up on unmount. Must be rendered inside `<X2Provider>`.
 */
export function X2SourceView(props: X2SourceViewProps): ReactElement {
  return <WebcamStream {...props} track="source" />;
}
