// Copyright (c) 2026 Reactor Technologies, Inc. All rights reserved.

// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: lingbot-v2 v0.1.1

import { Reactor, FileRef } from "@reactor-team/js-sdk";
export { FileRef };

export const MODEL_NAME = "reactor/lingbot-v2" as const;
export const MODEL_VERSION = "v0.1.1" as const;

/**
 * Preset media tracks for the LingbotV2 model.
 *
 * Declared in the model's OpenAPI schema and passed to the SDK as
 * `modelTracks` so the transport can prepare the SDP offer in
 * parallel with session polling (faster first-frame latency).
 */
export const LingbotV2Tracks = [
  { name: "main_video", kind: "video", direction: "recvonly" },
] as const;

/** Track names the client can subscribe to (recvonly, from the client's perspective). */
export type LingbotV2RecvTrackName = "main_video";

/** Set seed */
export interface LingbotV2SetSeedParams {
  /**
   * Seed for the random generator used to sample the initial noise. Must be a non-negative integer; the model never draws its own random seed — pick one explicitly (or keep the default) for reproducible runs. Read once when `start` fires; later changes take effect only after `reset` followed by a new `start`.
   * @minimum 0
   * @default 42
   */

  seed?: number;
}

/** Provide a reference image that anchors generation (image-to-video). Call before `start`; the image is required for generation to begin. Changes during generation have no effect until `reset` is issued and `start` is called again. Emits `image_accepted`, `conditions_ready`, and `state` on success, or `command_error` if the file is missing, not an image, or cannot be decoded. */
export interface LingbotV2SetImageParams {
  /**
   * Reference to a file uploaded via the Reactor presigned-URL protocol.
   * @default null
   */

  image?: FileRef;
}

/** Set the scene prompt. Valid at any time — call before `start` to arm generation, or hot-swap during generation to steer the next chunk. Emits `prompt_accepted`, `conditions_ready`, and `state` on success. */
export interface LingbotV2SetPromptParams {
  /**
   * Natural-language description of the scene to generate. Replaces the previously active prompt. Applied on the next chunk when generating; otherwise takes effect when `start` fires.
   * @default ""
   */

  prompt?: string;
}

/** Set camera_pose */
export interface LingbotV2SetCameraPoseParams {
  /**
   * Native camera-pose layer: a flat list of per-frame motion deltas, length a multiple of 6 — `[rx, ry, rz, tx, ty, tz]` per frame (small Euler-radian rotation + translation, in the camera-local frame). 6 floats = one delta applied to the whole chunk; 6*chunk_size = one delta per latent frame; any other 6*k is resampled to chunk_size. When active, rotation OVERRIDES look_horizontal / look_vertical and translation ADDS to WASD movement. Inputs are sanitized (NaN/Inf→0, rotations clamped to ±pi, translation to ±100), so any payload is safe. Pass an empty list (or omit) to deactivate.
   * @maxLength 1536
   * @default null
   */

  camera_pose?: unknown[];
}

/** Set move_lateral */
export interface LingbotV2SetMoveLateralParams {
  /**
   * Lateral (strafe left/right) camera translation. `idle` holds position; `strafe_left` / `strafe_right` translate sideways. Independent of `move_longitudinal` — both can be active together for diagonal movement. Can be changed at any time; the new value applies to the next chunk.
   * @default "idle"
   */

  move_lateral?: "idle" | "strafe_left" | "strafe_right";
}

/** Set look_vertical */
export interface LingbotV2SetLookVerticalParams {
  /**
   * Vertical (pitch) camera rotation. `idle` holds pitch steady; `up` / `down` rotate the camera at the rate given by `rotation_speed_deg`. Can be changed at any time; the new value applies to the next chunk.
   * @default "idle"
   */

  look_vertical?: "idle" | "up" | "down";
}

/** Set look_horizontal */
export interface LingbotV2SetLookHorizontalParams {
  /**
   * Horizontal (yaw) camera rotation. `idle` holds yaw steady; `left` / `right` rotate the camera at the rate given by `rotation_speed_deg`. Can be changed at any time; the new value applies to the next chunk.
   * @default "idle"
   */

  look_horizontal?: "idle" | "left" | "right";
}

/** Set move_longitudinal */
export interface LingbotV2SetMoveLongitudinalParams {
  /**
   * Longitudinal (forward/back) camera translation. `idle` holds position; `forward` / `back` translate along the look axis. Independent of `move_lateral` — both can be active together for diagonal movement. Can be changed at any time; the new value applies to the next chunk.
   * @default "idle"
   */

  move_longitudinal?: "idle" | "forward" | "back";
}

/** Set rotation_speed_deg */
export interface LingbotV2SetRotationSpeedDegParams {
  /**
   * Camera rotation speed in degrees per latent frame, applied when `look_horizontal` or `look_vertical` is not `idle`. Range 0.0 – 30.0. Ignored when both look axes are `idle`. Can be changed at any time; the new value applies to the next chunk.
   * @minimum 0
   * @maximum 30
   * @default 5
   */

  rotation_speed_deg?: number;
}

/**
 * Snapshot of the session's observable state.
 *
 * Emitted on connect, after every command that mutates session state (`set_prompt`, `set_image`, `start`, `pause`, `resume`, `reset`, and the auto-generated `set_<field>` setters), and after each `chunk_complete`. Clients can treat this as the single source of truth for driving UI, without having to track every individual command and message themselves.
 */
export interface LingbotV2StateMessage {
  type: "state";
  /** Current value of the `seed` input field. The seed that was actually used by the running generation was captured when `start` fired — later changes to `seed` only take effect after `reset` and a new `start`. */

  seed: number;
  /** True while generation is paused via `pause`. */

  paused: boolean;
  /** True while the chunk loop is actively producing frames — equivalent to `started and not paused`. `False` both before `start` and while paused; read `started` to disambiguate. */

  running: boolean;
  /** True once `start` has been accepted. Remains true while paused; reset to false by `reset` or after `generation_complete` when the session is not auto-restarting. */

  started: boolean;
  /** True once a reference image has been set for the session. */

  has_image: boolean;
  /** True once a prompt has been set for the session. */

  has_prompt: boolean;
  /** Current value of the `move_lateral` input field. */

  move_lateral: string;
  /** Zero-based index of the last completed chunk. `0` before the first chunk has completed, and resets to `0` on `reset`. */

  current_chunk: number;
  /** Current value of the `look_vertical` input field. */

  look_vertical: string;
  /** Composite action string derived from `move_longitudinal`, `move_lateral`, `look_horizontal`, and `look_vertical` — a `+`-joined combination of `w`/`s`/`a`/`d` and `left`/`right`/`up`/`down`, or `still` when idle. */

  current_action: string;
  /** The prompt currently driving generation, or `null` if no prompt has been set for the session. */

  current_prompt: unknown;
  /** Current value of the `look_horizontal` input field. */

  look_horizontal: string;
  /** Current value of the `move_longitudinal` input field. */

  move_longitudinal: string;
  /** True when a non-empty `camera_pose` has been set. */

  camera_pose_active: boolean;
  /** Current value of the `rotation_speed_deg` input field (0.0 – 30.0). */

  rotation_speed_deg: number;
}

/** Emitted when a command is rejected because preconditions are not met or its arguments could not be processed. */
export interface LingbotV2CommandErrorMessage {
  type: "command_error";
  /** Human-readable explanation of why the command was rejected. */

  reason: string;
  /** Name of the command that was rejected. */

  command: string;
}

/** Emitted once per completed chunk of `main_video`. */
export interface LingbotV2ChunkCompleteMessage {
  type: "chunk_complete";
  /** Zero-based index of the chunk that just completed. */

  chunk_index: number;
  /** The composite action string used to drive this chunk — a `+`-joined combination of translation (`w`/`s`/`a`/`d`) and look directions (`left`/`right`/`up`/`down`), or `still` when the camera is stationary. */

  active_action: string;
  /** The prompt that was active while this chunk was generated. */

  active_prompt: string;
  /** Number of pixel frames emitted by this chunk. */

  frames_emitted: number;
}

/** Emitted after `set_image` successfully decodes the uploaded file. */
export interface LingbotV2ImageAcceptedMessage {
  type: "image_accepted";
  /** Width in pixels of the decoded reference image. */

  width: number;
  /** Height in pixels of the decoded reference image. */

  height: number;
}

/** Emitted after `set_prompt` is accepted. */
export interface LingbotV2PromptAcceptedMessage {
  type: "prompt_accepted";
  /** The prompt text that was accepted. */

  prompt: string;
}

/** Emitted after `set_prompt` or `set_image` so the client can tell at a glance whether `start` will succeed. */
export interface LingbotV2ConditionsReadyMessage {
  type: "conditions_ready";
  /** True once a reference image has been set for the session. */

  has_image: boolean;
  /** True once a prompt has been set for the session. */

  has_prompt: boolean;
}

/** Emitted after `reset` clears session state and returns to the waiting state. */
export interface LingbotV2GenerationResetMessage {
  type: "generation_reset";
  /** Short human-readable reason the reset was issued. */

  reason: string;
}

/** Emitted in response to `pause`, once the current chunk finishes. */
export interface LingbotV2GenerationPausedMessage {
  type: "generation_paused";
  /** Index of the last completed chunk before pausing. */

  chunk_index: number;
}

/** Emitted in response to `resume` when leaving the paused state. */
export interface LingbotV2GenerationResumedMessage {
  type: "generation_resumed";
  /** Index of the last completed chunk before resuming. */

  chunk_index: number;
}

/** Emitted once when `start` succeeds and frames begin streaming. */
export interface LingbotV2GenerationStartedMessage {
  type: "generation_started";
  /** The prompt active at the start of generation. */

  prompt: string;
  /** Total number of chunks the run will produce before `generation_complete` fires. */

  chunk_num: number;
  /** Total number of pixel frames the run will emit on `main_video` before `generation_complete`. */

  frame_num: number;
}

/** Emitted when all `chunk_num` chunks of a run have streamed. If the session is still `started`, a new run kicks off immediately with the same prompt and image; call `reset` to stop. */
export interface LingbotV2GenerationCompleteMessage {
  type: "generation_complete";
  /** Total number of chunks produced by the run. */

  total_chunks: number;
}

export type LingbotV2Message =
  | LingbotV2StateMessage
  | LingbotV2CommandErrorMessage
  | LingbotV2ChunkCompleteMessage
  | LingbotV2ImageAcceptedMessage
  | LingbotV2PromptAcceptedMessage
  | LingbotV2ConditionsReadyMessage
  | LingbotV2GenerationResetMessage
  | LingbotV2GenerationPausedMessage
  | LingbotV2GenerationResumedMessage
  | LingbotV2GenerationStartedMessage
  | LingbotV2GenerationCompleteMessage;

/**
 * Options for creating a LingbotV2Model (model name is set automatically).
 *
 * Derived from `Reactor`'s own constructor options with `modelName`
 * and `modelTracks` removed — those are supplied by this class.
 * Any new option the SDK adds appears here automatically on the
 * next `defaultSdkVersion` bump.
 */
export type LingbotV2Options = Omit<
  ConstructorParameters<typeof Reactor>[0],
  "modelName" | "modelTracks"
>;

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Strongly-typed client for the LingbotV2 model.
 *
 * Extends {@link Reactor} with the model name (and modelTracks) baked into the
 * constructor, so every public method on Reactor — `connect`, `disconnect`,
 * `sendCommand`, `on`/`off`, `getStats`, `publishTrack`/`unpublishTrack`,
 * etc. — is reachable directly on the instance. The schema-derived sugar
 * below adds typed wrappers for every declared event, message, and track.
 */

export class LingbotV2Model extends Reactor {
  constructor(options?: LingbotV2Options) {
    super({
      ...options,
      modelName: MODEL_NAME,
      modelTracks: [...LingbotV2Tracks],
    });
  }

  /** @deprecated The model client now extends `Reactor` directly — call methods on `this` instead. This accessor returns `this` for backwards compatibility and will be removed in a future major release. */

  get reactor(): this {
    return this;
  }

  /** Pause generation after the current chunk finishes. Frames stop streaming on `main_video` until `resume` is called. Requires generation to be active. Emits `generation_paused` and `state` on success, or `command_error` if not generating or already paused. */

  async pause(): Promise<void> {
    await this.sendCommand("pause", {});
  }

  /** Abort the current run, clear the active prompt and reference image, and return to the waiting state. Valid at any time. After `reset`, call `set_prompt` and `set_image` again before `start` to begin a new session. Emits `generation_reset` and `state`. */

  async reset(): Promise<void> {
    await this.sendCommand("reset", {});
  }

  /** Begin generating video on `main_video`. Requires both a prompt (via `set_prompt`) and a reference image (via `set_image`). Emits `generation_started` and `state` on success, or `command_error` if a precondition is missing. Has no effect while already generating. */

  async start(): Promise<void> {
    await this.sendCommand("start", {});
  }

  /** Resume generation from a previous `pause`. Requires the session to be paused. Emits `generation_resumed` and `state` on success, or `command_error` if not paused. */

  async resume(): Promise<void> {
    await this.sendCommand("resume", {});
  }

  /**
   * Set seed
   * @param params - Set seed
   */

  async setSeed(params: LingbotV2SetSeedParams): Promise<void> {
    await this.sendCommand("set_seed", params);
  }

  /**
   * Provide a reference image that anchors generation (image-to-video). Call before `start`; the image is required for generation to begin. Changes during generation have no effect until `reset` is issued and `start` is called again. Emits `image_accepted`, `conditions_ready`, and `state` on success, or `command_error` if the file is missing, not an image, or cannot be decoded.
   * @param params - Provide a reference image that anchors generation (image-to-video). Call before `start`; the image is required for generation to begin. Changes during generation have no effect until `reset` is issued and `start` is called again. Emits `image_accepted`, `conditions_ready`, and `state` on success, or `command_error` if the file is missing, not an image, or cannot be decoded.
   */

  async setImage(params: LingbotV2SetImageParams): Promise<void> {
    await this.sendCommand("set_image", params);
  }

  /**
   * Set the scene prompt. Valid at any time — call before `start` to arm generation, or hot-swap during generation to steer the next chunk. Emits `prompt_accepted`, `conditions_ready`, and `state` on success.
   * @param params - Set the scene prompt. Valid at any time — call before `start` to arm generation, or hot-swap during generation to steer the next chunk. Emits `prompt_accepted`, `conditions_ready`, and `state` on success.
   */

  async setPrompt(params: LingbotV2SetPromptParams): Promise<void> {
    await this.sendCommand("set_prompt", params);
  }

  /**
   * Set camera_pose
   * @param params - Set camera_pose
   */

  async setCameraPose(params: LingbotV2SetCameraPoseParams): Promise<void> {
    await this.sendCommand("set_camera_pose", params);
  }

  /**
   * Set move_lateral
   * @param params - Set move_lateral
   */

  async setMoveLateral(params: LingbotV2SetMoveLateralParams): Promise<void> {
    await this.sendCommand("set_move_lateral", params);
  }

  /**
   * Set look_vertical
   * @param params - Set look_vertical
   */

  async setLookVertical(params: LingbotV2SetLookVerticalParams): Promise<void> {
    await this.sendCommand("set_look_vertical", params);
  }

  /**
   * Set look_horizontal
   * @param params - Set look_horizontal
   */

  async setLookHorizontal(
    params: LingbotV2SetLookHorizontalParams,
  ): Promise<void> {
    await this.sendCommand("set_look_horizontal", params);
  }

  /**
   * Set move_longitudinal
   * @param params - Set move_longitudinal
   */

  async setMoveLongitudinal(
    params: LingbotV2SetMoveLongitudinalParams,
  ): Promise<void> {
    await this.sendCommand("set_move_longitudinal", params);
  }

  /**
   * Set rotation_speed_deg
   * @param params - Set rotation_speed_deg
   */

  async setRotationSpeedDeg(
    params: LingbotV2SetRotationSpeedDegParams,
  ): Promise<void> {
    await this.sendCommand("set_rotation_speed_deg", params);
  }

  /**
   * Subscribe to typed model messages.
   * @param handler - Called with a discriminated LingbotV2Message
   * @returns Unsubscribe function
   */

  onMessage(handler: (message: LingbotV2Message) => void): () => void {
    const wrappedHandler = (raw: unknown) => {
      handler(_unwrapMessage<LingbotV2Message>(raw));
    };
    this.on("message", wrappedHandler);
    return () => this.off("message", wrappedHandler);
  }

  /**
   * Subscribe to "state" messages only.
   * @returns Unsubscribe function
   */

  onState(handler: (message: LingbotV2StateMessage) => void): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "state") handler(msg as LingbotV2StateMessage);
    });
  }

  /**
   * Subscribe to "command_error" messages only.
   * @returns Unsubscribe function
   */

  onCommandError(
    handler: (message: LingbotV2CommandErrorMessage) => void,
  ): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "command_error")
        handler(msg as LingbotV2CommandErrorMessage);
    });
  }

  /**
   * Subscribe to "chunk_complete" messages only.
   * @returns Unsubscribe function
   */

  onChunkComplete(
    handler: (message: LingbotV2ChunkCompleteMessage) => void,
  ): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "chunk_complete")
        handler(msg as LingbotV2ChunkCompleteMessage);
    });
  }

  /**
   * Subscribe to "image_accepted" messages only.
   * @returns Unsubscribe function
   */

  onImageAccepted(
    handler: (message: LingbotV2ImageAcceptedMessage) => void,
  ): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "image_accepted")
        handler(msg as LingbotV2ImageAcceptedMessage);
    });
  }

  /**
   * Subscribe to "prompt_accepted" messages only.
   * @returns Unsubscribe function
   */

  onPromptAccepted(
    handler: (message: LingbotV2PromptAcceptedMessage) => void,
  ): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "prompt_accepted")
        handler(msg as LingbotV2PromptAcceptedMessage);
    });
  }

  /**
   * Subscribe to "conditions_ready" messages only.
   * @returns Unsubscribe function
   */

  onConditionsReady(
    handler: (message: LingbotV2ConditionsReadyMessage) => void,
  ): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "conditions_ready")
        handler(msg as LingbotV2ConditionsReadyMessage);
    });
  }

  /**
   * Subscribe to "generation_reset" messages only.
   * @returns Unsubscribe function
   */

  onGenerationReset(
    handler: (message: LingbotV2GenerationResetMessage) => void,
  ): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "generation_reset")
        handler(msg as LingbotV2GenerationResetMessage);
    });
  }

  /**
   * Subscribe to "generation_paused" messages only.
   * @returns Unsubscribe function
   */

  onGenerationPaused(
    handler: (message: LingbotV2GenerationPausedMessage) => void,
  ): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "generation_paused")
        handler(msg as LingbotV2GenerationPausedMessage);
    });
  }

  /**
   * Subscribe to "generation_resumed" messages only.
   * @returns Unsubscribe function
   */

  onGenerationResumed(
    handler: (message: LingbotV2GenerationResumedMessage) => void,
  ): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "generation_resumed")
        handler(msg as LingbotV2GenerationResumedMessage);
    });
  }

  /**
   * Subscribe to "generation_started" messages only.
   * @returns Unsubscribe function
   */

  onGenerationStarted(
    handler: (message: LingbotV2GenerationStartedMessage) => void,
  ): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "generation_started")
        handler(msg as LingbotV2GenerationStartedMessage);
    });
  }

  /**
   * Subscribe to "generation_complete" messages only.
   * @returns Unsubscribe function
   */

  onGenerationComplete(
    handler: (message: LingbotV2GenerationCompleteMessage) => void,
  ): () => void {
    return this.onMessage((msg) => {
      if (msg.type === "generation_complete")
        handler(msg as LingbotV2GenerationCompleteMessage);
    });
  }

  /**
   * Subscribe to the "main_video" recvonly video track the model publishes.
   *
   * The handler fires once the model starts publishing this track; it receives the live MediaStreamTrack and the parent MediaStream (useful for attaching to a `<video>` / `<audio>` element via `srcObject`).
   * @param handler - Called with the received track and its stream
   * @returns Unsubscribe function
   */

  onMainVideo(
    handler: (track: MediaStreamTrack, stream: MediaStream) => void,
  ): () => void {
    const wrapped = (name: string, t: MediaStreamTrack, s: MediaStream) => {
      if (name === "main_video") handler(t, s);
    };
    this.on("trackReceived", wrapped);
    return () => this.off("trackReceived", wrapped);
  }
}
