// Copyright (c) 2026 Reactor Technologies, Inc. All rights reserved.

// Auto-generated by @reactor-team/codegen — DO NOT EDIT
// Model: lingbot-v2 v0.1.1

"use client";

import { type ReactElement } from "react";
import {
  ReactorProvider,
  useReactor,
  useReactorMessage,
  ReactorView,
  type ReactorViewProps,
} from "@reactor-team/js-sdk";
import {
  MODEL_NAME,
  LingbotV2Tracks,
  type LingbotV2Options,
  type LingbotV2SetSeedParams,
  type LingbotV2SetImageParams,
  type LingbotV2SetPromptParams,
  type LingbotV2SetCameraPoseParams,
  type LingbotV2SetMoveLateralParams,
  type LingbotV2SetLookVerticalParams,
  type LingbotV2SetLookHorizontalParams,
  type LingbotV2SetMoveLongitudinalParams,
  type LingbotV2SetRotationSpeedDegParams,
  type LingbotV2Message,
  type LingbotV2StateMessage,
  type LingbotV2CommandErrorMessage,
  type LingbotV2ChunkCompleteMessage,
  type LingbotV2ImageAcceptedMessage,
  type LingbotV2PromptAcceptedMessage,
  type LingbotV2ConditionsReadyMessage,
  type LingbotV2GenerationResetMessage,
  type LingbotV2GenerationPausedMessage,
  type LingbotV2GenerationResumedMessage,
  type LingbotV2GenerationStartedMessage,
  type LingbotV2GenerationCompleteMessage,
  type LingbotV2RecvTrackName,
} from "./lingbot-v2";

/**
 * @internal Flatten the `{ type, data, uploads? }` envelope the SDK
 * hands to `reactor.on("message", …)` so a field the model schema
 * declares on a message is reachable at `msg.<field>` — matching the
 * shape the exported message interfaces promise.
 */
function _unwrapMessage<T>(raw: unknown): T {
  const env = raw as { type?: string; data?: Record<string, unknown> };
  if (
    env &&
    typeof env === "object" &&
    env.data &&
    typeof env.data === "object"
  ) {
    return { ...env.data, type: env.type } as T;
  }
  return raw as T;
}

/**
 * Props for the {@link LingbotV2Provider} component.
 *
 * Derived from `ReactorProvider`'s own props, with `modelName` and
 * `modelTracks` stripped — those are supplied by this provider.
 */
export type LingbotV2ProviderProps = Omit<
  Parameters<typeof ReactorProvider>[0],
  "modelName" | "modelTracks"
>;

/**
 * Provider for the LingbotV2 model.
 *
 * Wraps {@link ReactorProvider} with `modelName` and `modelTracks` pre-configured from the
 * generated constants. Drop this near the top of your tree, then use
 * {@link useLingbotV2} and the `useLingbotV2<Message>` hooks below it.
 */
export function LingbotV2Provider({
  children,
  ...rest
}: LingbotV2ProviderProps): ReactElement {
  return (
    <ReactorProvider
      {...rest}
      modelName={MODEL_NAME}
      modelTracks={[...LingbotV2Tracks]}
    >
      {children}
    </ReactorProvider>
  );
}

/**
 * Access the LingbotV2 model as typed commands bound to the nearest
 * {@link LingbotV2Provider}.
 *
 * Returns the full action surface — every public field on the SDK's
 * `ReactorStore` (`status`, `sessionId`, `connect`, `disconnect`,
 * `sendCommand`, `uploadFile`, `publish`, `unpublish`, `reconnect`,
 * …) is exposed automatically, alongside one typed method per
 * model event.
 *
 * Fields are pulled off the store one at a time so Zustand's
 * shallow-equality selector keeps each subscription scoped — a
 * component reading only `status` doesn't re-render when
 * `sessionExpiration` changes. Future SDK releases that add new
 * store fields flow into this hook on the next codegen run with no
 * hand-edit (the field list is derived from `js-sdk`'s d.ts via
 * `loadReactorStoreFieldsFromDts` in `sdk-surface.ts`).
 */
export function useLingbotV2() {
  const connect = useReactor((s) => s.connect);
  const connectOptions = useReactor((s) => s.connectOptions);
  const disconnect = useReactor((s) => s.disconnect);
  const downloadClipAsFile = useReactor((s) => s.downloadClipAsFile);
  const jwtToken = useReactor((s) => s.jwtToken);
  const lastError = useReactor((s) => s.lastError);
  const publish = useReactor((s) => s.publish);
  const reconnect = useReactor((s) => s.reconnect);
  const requestClip = useReactor((s) => s.requestClip);
  const requestRecording = useReactor((s) => s.requestRecording);
  const sendCommand = useReactor((s) => s.sendCommand);
  const sessionExpiration = useReactor((s) => s.sessionExpiration);
  const sessionId = useReactor((s) => s.sessionId);
  const status = useReactor((s) => s.status);
  const tracks = useReactor((s) => s.tracks);
  const unpublish = useReactor((s) => s.unpublish);
  const uploadFile = useReactor((s) => s.uploadFile);

  return {
    connect,
    connectOptions,
    disconnect,
    downloadClipAsFile,
    jwtToken,
    lastError,
    publish,
    reconnect,
    requestClip,
    requestRecording,
    sendCommand,
    sessionExpiration,
    sessionId,
    status,
    tracks,
    unpublish,
    uploadFile,
    pause: (): Promise<void> => sendCommand("pause", {}),
    reset: (): Promise<void> => sendCommand("reset", {}),
    start: (): Promise<void> => sendCommand("start", {}),
    resume: (): Promise<void> => sendCommand("resume", {}),
    setSeed: (params: LingbotV2SetSeedParams): Promise<void> =>
      sendCommand("set_seed", params),
    setImage: (params: LingbotV2SetImageParams): Promise<void> =>
      sendCommand("set_image", params),
    setPrompt: (params: LingbotV2SetPromptParams): Promise<void> =>
      sendCommand("set_prompt", params),
    setCameraPose: (params: LingbotV2SetCameraPoseParams): Promise<void> =>
      sendCommand("set_camera_pose", params),
    setMoveLateral: (params: LingbotV2SetMoveLateralParams): Promise<void> =>
      sendCommand("set_move_lateral", params),
    setLookVertical: (params: LingbotV2SetLookVerticalParams): Promise<void> =>
      sendCommand("set_look_vertical", params),
    setLookHorizontal: (
      params: LingbotV2SetLookHorizontalParams,
    ): Promise<void> => sendCommand("set_look_horizontal", params),
    setMoveLongitudinal: (
      params: LingbotV2SetMoveLongitudinalParams,
    ): Promise<void> => sendCommand("set_move_longitudinal", params),
    setRotationSpeedDeg: (
      params: LingbotV2SetRotationSpeedDegParams,
    ): Promise<void> => sendCommand("set_rotation_speed_deg", params),
  };
}

/**
 * Subscribe to any LingbotV2 message with a fully-typed handler.
 * The handler receives a discriminated LingbotV2Message.
 */
export function useLingbotV2Message(
  handler: (message: LingbotV2Message) => void,
): void {
  useReactorMessage((msg: unknown) =>
    handler(_unwrapMessage<LingbotV2Message>(msg)),
  );
}

/**
 * Subscribe to "state" messages only.
 * Handler receives a fully-typed LingbotV2StateMessage.
 */
export function useLingbotV2State(
  handler: (message: LingbotV2StateMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<LingbotV2Message>(msg);
    if (m.type === "state") {
      handler(m as LingbotV2StateMessage);
    }
  });
}

/**
 * Subscribe to "command_error" messages only.
 * Handler receives a fully-typed LingbotV2CommandErrorMessage.
 */
export function useLingbotV2CommandError(
  handler: (message: LingbotV2CommandErrorMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<LingbotV2Message>(msg);
    if (m.type === "command_error") {
      handler(m as LingbotV2CommandErrorMessage);
    }
  });
}

/**
 * Subscribe to "chunk_complete" messages only.
 * Handler receives a fully-typed LingbotV2ChunkCompleteMessage.
 */
export function useLingbotV2ChunkComplete(
  handler: (message: LingbotV2ChunkCompleteMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<LingbotV2Message>(msg);
    if (m.type === "chunk_complete") {
      handler(m as LingbotV2ChunkCompleteMessage);
    }
  });
}

/**
 * Subscribe to "image_accepted" messages only.
 * Handler receives a fully-typed LingbotV2ImageAcceptedMessage.
 */
export function useLingbotV2ImageAccepted(
  handler: (message: LingbotV2ImageAcceptedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<LingbotV2Message>(msg);
    if (m.type === "image_accepted") {
      handler(m as LingbotV2ImageAcceptedMessage);
    }
  });
}

/**
 * Subscribe to "prompt_accepted" messages only.
 * Handler receives a fully-typed LingbotV2PromptAcceptedMessage.
 */
export function useLingbotV2PromptAccepted(
  handler: (message: LingbotV2PromptAcceptedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<LingbotV2Message>(msg);
    if (m.type === "prompt_accepted") {
      handler(m as LingbotV2PromptAcceptedMessage);
    }
  });
}

/**
 * Subscribe to "conditions_ready" messages only.
 * Handler receives a fully-typed LingbotV2ConditionsReadyMessage.
 */
export function useLingbotV2ConditionsReady(
  handler: (message: LingbotV2ConditionsReadyMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<LingbotV2Message>(msg);
    if (m.type === "conditions_ready") {
      handler(m as LingbotV2ConditionsReadyMessage);
    }
  });
}

/**
 * Subscribe to "generation_reset" messages only.
 * Handler receives a fully-typed LingbotV2GenerationResetMessage.
 */
export function useLingbotV2GenerationReset(
  handler: (message: LingbotV2GenerationResetMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<LingbotV2Message>(msg);
    if (m.type === "generation_reset") {
      handler(m as LingbotV2GenerationResetMessage);
    }
  });
}

/**
 * Subscribe to "generation_paused" messages only.
 * Handler receives a fully-typed LingbotV2GenerationPausedMessage.
 */
export function useLingbotV2GenerationPaused(
  handler: (message: LingbotV2GenerationPausedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<LingbotV2Message>(msg);
    if (m.type === "generation_paused") {
      handler(m as LingbotV2GenerationPausedMessage);
    }
  });
}

/**
 * Subscribe to "generation_resumed" messages only.
 * Handler receives a fully-typed LingbotV2GenerationResumedMessage.
 */
export function useLingbotV2GenerationResumed(
  handler: (message: LingbotV2GenerationResumedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<LingbotV2Message>(msg);
    if (m.type === "generation_resumed") {
      handler(m as LingbotV2GenerationResumedMessage);
    }
  });
}

/**
 * Subscribe to "generation_started" messages only.
 * Handler receives a fully-typed LingbotV2GenerationStartedMessage.
 */
export function useLingbotV2GenerationStarted(
  handler: (message: LingbotV2GenerationStartedMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<LingbotV2Message>(msg);
    if (m.type === "generation_started") {
      handler(m as LingbotV2GenerationStartedMessage);
    }
  });
}

/**
 * Subscribe to "generation_complete" messages only.
 * Handler receives a fully-typed LingbotV2GenerationCompleteMessage.
 */
export function useLingbotV2GenerationComplete(
  handler: (message: LingbotV2GenerationCompleteMessage) => void,
): void {
  useReactorMessage((msg: unknown) => {
    const m = _unwrapMessage<LingbotV2Message>(msg);
    if (m.type === "generation_complete") {
      handler(m as LingbotV2GenerationCompleteMessage);
    }
  });
}

/**
 * Subscribe to a recvonly MediaStreamTrack the model publishes, by name.
 *
 * Returns `undefined` until the model emits the track, then the live track for the lifetime of the connection. `name` is constrained to the model's declared recvonly channels — use one of `LingbotV2RecvTrackName`.
 * @param name - A recvonly track name declared by the model
 * @returns The live MediaStreamTrack, or `undefined` until received
 */
export function useLingbotV2Track(
  name: LingbotV2RecvTrackName,
): MediaStreamTrack | undefined {
  return useReactor((s) => s.tracks[name]);
}

export type LingbotV2MainVideoViewProps = Omit<ReactorViewProps, "track">;

/**
 * Render the model's "main_video" recvonly video track in a `<video>` element.
 *
 * Thin wrapper around `<ReactorView>` with `track` pre-bound. Accepts every other `ReactorViewProps` (`audioTrack`, `className`, `style`, `videoObjectFit`, `muted`, …). Must be rendered inside `<LingbotV2Provider>`.
 */
export function LingbotV2MainVideoView(
  props: LingbotV2MainVideoViewProps,
): ReactElement {
  return <ReactorView {...props} track="main_video" />;
}
